package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Archivage generated by hbm2java
 */
@Entity
@Table(name = "archivage", catalog = "chalenger")
public class Archivage implements java.io.Serializable {

	private int idArchivage;
	private Collaborateur collaborateur;
	private Poste poste;
	private String date;
	private String salaire;

	public Archivage() {
	}

	public Archivage(int idArchivage, Collaborateur collaborateur, Poste poste) {
		this.idArchivage = idArchivage;
		this.collaborateur = collaborateur;
		this.poste = poste;
	}

	public Archivage(int idArchivage, Collaborateur collaborateur, Poste poste,
			String date, String salaire) {
		this.idArchivage = idArchivage;
		this.collaborateur = collaborateur;
		this.poste = poste;
		this.date = date;
		this.salaire = salaire;
	}

	@Id
	@Column(name = "Id_archivage", unique = true, nullable = false)
	public int getIdArchivage() {
		return this.idArchivage;
	}

	public void setIdArchivage(int idArchivage) {
		this.idArchivage = idArchivage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Matricule", nullable = false)
	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_poste", nullable = false)
	public Poste getPoste() {
		return this.poste;
	}

	public void setPoste(Poste poste) {
		this.poste = poste;
	}

	@Column(name = "Date", length = 254)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "Salaire", length = 254)
	public String getSalaire() {
		return this.salaire;
	}

	public void setSalaire(String salaire) {
		this.salaire = salaire;
	}

}
