package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Competence generated by hbm2java
 */
@Entity
@Table(name = "competence", catalog = "chalenger")
public class Competence implements java.io.Serializable {

	private int idCompetence;
	private Integer libeleCompetence;
	private Set<Niveau> niveaus = new HashSet<Niveau>(0);

	public Competence() {
	}

	public Competence(int idCompetence) {
		this.idCompetence = idCompetence;
	}

	public Competence(int idCompetence, Integer libeleCompetence,
			Set<Niveau> niveaus) {
		this.idCompetence = idCompetence;
		this.libeleCompetence = libeleCompetence;
		this.niveaus = niveaus;
	}

	@Id
	@Column(name = "Id_competence", unique = true, nullable = false)
	public int getIdCompetence() {
		return this.idCompetence;
	}

	public void setIdCompetence(int idCompetence) {
		this.idCompetence = idCompetence;
	}

	@Column(name = "Libele_competence")
	public Integer getLibeleCompetence() {
		return this.libeleCompetence;
	}

	public void setLibeleCompetence(Integer libeleCompetence) {
		this.libeleCompetence = libeleCompetence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competence")
	public Set<Niveau> getNiveaus() {
		return this.niveaus;
	}

	public void setNiveaus(Set<Niveau> niveaus) {
		this.niveaus = niveaus;
	}

}
