package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "diplome", catalog = "chalenger")
public class Diplome implements java.io.Serializable {

	private int idDiplome;
	private String libelleDiplome;
	private String typeDiplome;
	private Set<ObtenirDiplome> obtenirDiplomes = new HashSet<ObtenirDiplome>(0);

	public Diplome() {
	}

	public Diplome(int idDiplome) {
		this.idDiplome = idDiplome;
	}

	public Diplome(int idDiplome, String libelleDiplome, String typeDiplome,
			Set<ObtenirDiplome> obtenirDiplomes) {
		this.idDiplome = idDiplome;
		this.libelleDiplome = libelleDiplome;
		this.typeDiplome = typeDiplome;
		this.obtenirDiplomes = obtenirDiplomes;
	}

	@Id
	@Column(name = "Id_diplome", unique = true, nullable = false)
	public int getIdDiplome() {
		return this.idDiplome;
	}

	public void setIdDiplome(int idDiplome) {
		this.idDiplome = idDiplome;
	}

	@Column(name = "libelle_diplome", length = 254)
	public String getLibelleDiplome() {
		return this.libelleDiplome;
	}

	public void setLibelleDiplome(String libelleDiplome) {
		this.libelleDiplome = libelleDiplome;
	}

	@Column(name = "Type_diplome", length = 254)
	public String getTypeDiplome() {
		return this.typeDiplome;
	}

	public void setTypeDiplome(String typeDiplome) {
		this.typeDiplome = typeDiplome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diplome")
	public Set<ObtenirDiplome> getObtenirDiplomes() {
		return this.obtenirDiplomes;
	}

	public void setObtenirDiplomes(Set<ObtenirDiplome> obtenirDiplomes) {
		this.obtenirDiplomes = obtenirDiplomes;
	}

}
