package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ManagerRhId generated by hbm2java
 */
@Embeddable
public class ManagerRhId implements java.io.Serializable {

	private int matricule;
	private int idManagerRh;

	public ManagerRhId() {
	}

	public ManagerRhId(int matricule, int idManagerRh) {
		this.matricule = matricule;
		this.idManagerRh = idManagerRh;
	}

	@Column(name = "Matricule", nullable = false)
	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	@Column(name = "Id_manager_RH", nullable = false)
	public int getIdManagerRh() {
		return this.idManagerRh;
	}

	public void setIdManagerRh(int idManagerRh) {
		this.idManagerRh = idManagerRh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ManagerRhId))
			return false;
		ManagerRhId castOther = (ManagerRhId) other;

		return (this.getMatricule() == castOther.getMatricule())
				&& (this.getIdManagerRh() == castOther.getIdManagerRh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatricule();
		result = 37 * result + this.getIdManagerRh();
		return result;
	}

}
