package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "chalenger")
public class Niveau implements java.io.Serializable {

	private int idNiveau;
	private Competence competence;
	private Technologie technologie;
	private Collaborateur collaborateur;
	private Integer niveau;

	public Niveau() {
	}

	public Niveau(int idNiveau, Competence competence, Technologie technologie,
			Collaborateur collaborateur) {
		this.idNiveau = idNiveau;
		this.competence = competence;
		this.technologie = technologie;
		this.collaborateur = collaborateur;
	}

	public Niveau(int idNiveau, Competence competence, Technologie technologie,
			Collaborateur collaborateur, Integer niveau) {
		this.idNiveau = idNiveau;
		this.competence = competence;
		this.technologie = technologie;
		this.collaborateur = collaborateur;
		this.niveau = niveau;
	}

	@Id
	@Column(name = "Id_niveau", unique = true, nullable = false)
	public int getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_competence", nullable = false)
	public Competence getCompetence() {
		return this.competence;
	}

	public void setCompetence(Competence competence) {
		this.competence = competence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_technologie", nullable = false)
	public Technologie getTechnologie() {
		return this.technologie;
	}

	public void setTechnologie(Technologie technologie) {
		this.technologie = technologie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Matricule", nullable = false)
	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	@Column(name = "Niveau")
	public Integer getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Integer niveau) {
		this.niveau = niveau;
	}

}
