package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObtenirDiplome generated by hbm2java
 */
@Entity
@Table(name = "obtenir_diplome", catalog = "chalenger")
public class ObtenirDiplome implements java.io.Serializable {

	private int idObtention;
	private Diplome diplome;
	private Ecole ecole;
	private Collaborateur collaborateur;
	private Integer promotion;

	public ObtenirDiplome() {
	}

	public ObtenirDiplome(int idObtention, Diplome diplome, Ecole ecole,
			Collaborateur collaborateur) {
		this.idObtention = idObtention;
		this.diplome = diplome;
		this.ecole = ecole;
		this.collaborateur = collaborateur;
	}

	public ObtenirDiplome(int idObtention, Diplome diplome, Ecole ecole,
			Collaborateur collaborateur, Integer promotion) {
		this.idObtention = idObtention;
		this.diplome = diplome;
		this.ecole = ecole;
		this.collaborateur = collaborateur;
		this.promotion = promotion;
	}

	@Id
	@Column(name = "id_obtention", unique = true, nullable = false)
	public int getIdObtention() {
		return this.idObtention;
	}

	public void setIdObtention(int idObtention) {
		this.idObtention = idObtention;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_diplome", nullable = false)
	public Diplome getDiplome() {
		return this.diplome;
	}

	public void setDiplome(Diplome diplome) {
		this.diplome = diplome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_ecole", nullable = false)
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Matricule", nullable = false)
	public Collaborateur getCollaborateur() {
		return this.collaborateur;
	}

	public void setCollaborateur(Collaborateur collaborateur) {
		this.collaborateur = collaborateur;
	}

	@Column(name = "promotion")
	public Integer getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Integer promotion) {
		this.promotion = promotion;
	}

}
