package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poste generated by hbm2java
 */
@Entity
@Table(name = "poste", catalog = "chalenger")
public class Poste implements java.io.Serializable {

	private int idPoste;
	private String libellePoste1;
	private String libellePoste2;
	private Set<Archivage> archivages = new HashSet<Archivage>(0);

	public Poste() {
	}

	public Poste(int idPoste) {
		this.idPoste = idPoste;
	}

	public Poste(int idPoste, String libellePoste1, String libellePoste2,
			Set<Archivage> archivages) {
		this.idPoste = idPoste;
		this.libellePoste1 = libellePoste1;
		this.libellePoste2 = libellePoste2;
		this.archivages = archivages;
	}

	@Id
	@Column(name = "Id_poste", unique = true, nullable = false)
	public int getIdPoste() {
		return this.idPoste;
	}

	public void setIdPoste(int idPoste) {
		this.idPoste = idPoste;
	}

	@Column(name = "Libelle_poste1", length = 254)
	public String getLibellePoste1() {
		return this.libellePoste1;
	}

	public void setLibellePoste1(String libellePoste1) {
		this.libellePoste1 = libellePoste1;
	}

	@Column(name = "Libelle_poste2", length = 254)
	public String getLibellePoste2() {
		return this.libellePoste2;
	}

	public void setLibellePoste2(String libellePoste2) {
		this.libellePoste2 = libellePoste2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poste")
	public Set<Archivage> getArchivages() {
		return this.archivages;
	}

	public void setArchivages(Set<Archivage> archivages) {
		this.archivages = archivages;
	}

}
