package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "chalenger")
public class Profile implements java.io.Serializable {

	private int idProfile;
	private String libelleProfile;
	private Set<User> users = new HashSet<User>(0);

	public Profile() {
	}

	public Profile(int idProfile) {
		this.idProfile = idProfile;
	}

	public Profile(int idProfile, String libelleProfile, Set<User> users) {
		this.idProfile = idProfile;
		this.libelleProfile = libelleProfile;
		this.users = users;
	}

	@Id
	@Column(name = "Id_profile", unique = true, nullable = false)
	public int getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(int idProfile) {
		this.idProfile = idProfile;
	}

	@Column(name = "Libelle_profile", length = 254)
	public String getLibelleProfile() {
		return this.libelleProfile;
	}

	public void setLibelleProfile(String libelleProfile) {
		this.libelleProfile = libelleProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
