package com.sqli.beans;

// Generated 30 déc. 2013 23:37:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Technologie generated by hbm2java
 */
@Entity
@Table(name = "technologie", catalog = "chalenger")
public class Technologie implements java.io.Serializable {

	private int idTechnologie;
	private String libelleTechnologie;
	private Set<Niveau> niveaus = new HashSet<Niveau>(0);

	public Technologie() {
	}

	public Technologie(int idTechnologie) {
		this.idTechnologie = idTechnologie;
	}

	public Technologie(int idTechnologie, String libelleTechnologie,
			Set<Niveau> niveaus) {
		this.idTechnologie = idTechnologie;
		this.libelleTechnologie = libelleTechnologie;
		this.niveaus = niveaus;
	}

	@Id
	@Column(name = "Id_technologie", unique = true, nullable = false)
	public int getIdTechnologie() {
		return this.idTechnologie;
	}

	public void setIdTechnologie(int idTechnologie) {
		this.idTechnologie = idTechnologie;
	}

	@Column(name = "Libelle_technologie", length = 254)
	public String getLibelleTechnologie() {
		return this.libelleTechnologie;
	}

	public void setLibelleTechnologie(String libelleTechnologie) {
		this.libelleTechnologie = libelleTechnologie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "technologie")
	public Set<Niveau> getNiveaus() {
		return this.niveaus;
	}

	public void setNiveaus(Set<Niveau> niveaus) {
		this.niveaus = niveaus;
	}

}
